// importint a type definition for 'Metadata' from 'next'
import type { Metadata } from 'next'
// import a font named 'Inter' from Google fonts through Next.js
import { Inter } from 'next/font/google'
// importing a blobal css file
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tic-Tac Toe Game',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
