// importint a type definition for 'Metadata' from 'next'
import type { Metadata } from 'next'
// import a font named 'Inter' from Google fonts through Next.js
import { Inter } from 'next/font/google'
// importing a blobal css file
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Tic-Tac Toe Game',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	)
}

/*
Purpose: This file defines a layout component, RootLayout, which is a React component used to wrap around other components or pages in your application.
Content:
    It imports the type Metadata from Next.js, likely used for defining page metadata.
    It imports and uses the Google font 'Inter' and includes the global CSS file (globals.css).
    The RootLayout component itself takes children as a prop and renders them within a basic HTML structure.
Usage: This layout can be applied to any page in your app to ensure a consistent look and feel. It also applies the 'Inter' font class to the body of the pages where it's used.
*/
